databases:
  - name: milan-db
    databaseName: chitti_apps
    user: milan
    plan: free

services:
  - type: web
    name: milan-be
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: DB_CON_STR
        fromDatabase:
          name: milan-db
          property: connectionString
